Statically link zlib in build scripts
Avoids libz.so.1 not found at runtime inside the Nix sandbox.

Error message:
error: failed to run custom build command for `cargo v0.88.0 (/build/rust-mos-src-vendored-1.87.0-dev/src/tools/cargo)`

Caused by:
  process didn't exit successfully: `/build/rust-mos-src-vendored-1.87.0-dev/build/x86_64-unknown-linux-gnu/stage1-tools/release/build/cargo-4a91e456114b2c43/build-script-build` (exit status: 127)
  --- stderr
  /build/rust-mos-src-vendored-1.87.0-dev/build/x86_64-unknown-linux-gnu/stage1-tools/release/build/cargo-4a91e456114b2c43/build-script-build: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory