Ignore rustfmt's missing librustc_driver at patchelf time
rustfmt is nightly-built while the rest of the bundle is beta; its
librustc_driver-*.so is not present and will never be found. rustfmt
is unused by the rust-mos build itself.
The error message is:
auto-patchelf: 1 dependencies could not be satisfied
error: auto-patchelf could not satisfy dependency librustc_driver-0f916e861b45e5f3.so wanted by /nix/store/3dli4qk86y34l78agzz5isf6qa2f8szg-rust-mos-stage0-1.85.0-beta-2025-02-18/bin/rustfmt